// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHG9tC3oF78ui7Y7s_D_rxA8hoDp8RMa8',
    appId: '1:305583308200:android:a53c2be12ff769de37719d',
    messagingSenderId: '305583308200',
    projectId: 'appgricole-4b139',
    databaseURL: 'https://appgricole-4b139-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appgricole-4b139.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLZyPssuPThhjqJMfONx-ppnuIIscxZ8M',
    appId: '1:305583308200:ios:ea9563164a0989d237719d',
    messagingSenderId: '305583308200',
    projectId: 'appgricole-4b139',
    databaseURL: 'https://appgricole-4b139-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appgricole-4b139.appspot.com',
    androidClientId: '305583308200-93kedhivo6jf49rp8umk08schq19doli.apps.googleusercontent.com',
    iosClientId: '305583308200-u2etd2ndlduasemdr4nnk9ul1pg3i5bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.desktop',
  );
}
